/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import { QueryLogItem, KPICardItem, ModelMetric } from './aiTypes';

export const INITIAL_KPIS: KPICardItem[] = [
  {
    id: 'kpi-queries',
    title: 'Queries',
    value: '24,892',
    numericValue: 24892,
    trend: '+12.4%',
    trendIsPositive: true,
    icon: 'queries',
    // Sparkline points for curvy smooth line in screenshot
    sparkline: [20, 32, 25, 45, 30, 48, 42, 60],
    sparklineColor: '#EC4899', // pink/magenta
  },
  {
    id: 'kpi-success',
    title: 'Success rate',
    value: '8,421',
    numericValue: 8421,
    trend: '+8.7%',
    trendIsPositive: true,
    icon: 'success',
    sparkline: [30, 22, 40, 28, 50, 45, 58, 65],
    sparklineColor: '#8B5CF6', // purple
  },
  {
    id: 'kpi-failed',
    title: 'Failed',
    value: '4,114',
    numericValue: 4114,
    trend: '-5.2%',
    trendIsPositive: false,
    icon: 'failed',
    sparkline: [45, 38, 52, 35, 40, 30, 28, 22],
    sparklineColor: '#6366F1', // indigo
  },
  {
    id: 'kpi-flagged',
    title: 'Flagged',
    value: '286',
    numericValue: 286,
    trend: '+4.4%',
    trendIsPositive: true,
    icon: 'flagged',
    sparkline: [15, 25, 20, 38, 28, 42, 36, 48],
    sparklineColor: '#F43F5E', // rose
  },
];

export const INITIAL_QUERIES: QueryLogItem[] = [
  {
    id: 'qry-101',
    query: 'Find me the best sushi place in downtown with outdoor seating and omakase options',
    category: 'Restaurant',
    user: 'Violet Norman',
    userEmail: 'violet.norman@example.com',
    userAvatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=100&h=100&fit=crop&crop=face',
    model: 'Monogram-GPT',
    status: 'Success',
    responseTime: 2.4,
    timestamp: '2 mins ago',
    tokensPrompt: 48,
    tokensCompletion: 312,
    cost: 0.0036,
    fullPrompt: 'Find me the best sushi place in downtown with outdoor seating and omakase options. Price range: $$$',
    responseText: 'Here are the top three recommendations in downtown:\n1. **Kuroshio Omakase** - Heated garden terrace, 14-course seasonal chef tasting.\n2. **Sushi Jin** - Rooftop patio with fresh Tokyo Tsukiji imports.\n3. **Mizumi Bistro** - Casual courtyard with excellent nigiri combos.',
    routingPath: 'SmartRouter > Tier-1 GPT Cache > Monogram-GPT (us-east)',
    latencyBreakdown: { dnsMs: 18, ttftMs: 420, generationMs: 1962 },
    clientIp: '192.168.1.42',
    temperature: 0.7,
  },
  {
    id: 'qry-102',
    query: 'Create an Extra Chewy Chocolate Chip Cookie recipe with brown butter and sea salt',
    category: 'Recipe',
    user: 'James Wilson',
    userEmail: 'j.wilson@craftbakery.io',
    userAvatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=100&h=100&fit=crop&crop=face',
    model: 'Monogram-GPT',
    status: 'Success',
    responseTime: 3.1,
    timestamp: '5 mins ago',
    tokensPrompt: 64,
    tokensCompletion: 490,
    cost: 0.0055,
    fullPrompt: 'Create an Extra Chewy Chocolate Chip Cookie recipe with browned butter, dark chocolate chunks, and flaky Maldon salt.',
    responseText: '### Ultra-Chewy Brown Butter Chocolate Chip Cookies\n\n**Key Secrets:**\n- Brown 1 cup unsalted butter until amber and nutty.\n- Use dark brown sugar (high molasses for chewiness).\n- Chill dough for at least 2 hours.\n- Bake at 350°F (175°C) for 10-11 minutes.\n- Immediately top with flaky Maldon sea salt.',
    routingPath: 'SmartRouter > Monogram-GPT (us-central)',
    latencyBreakdown: { dnsMs: 14, ttftMs: 380, generationMs: 2706 },
    clientIp: '10.0.4.12',
    temperature: 0.65,
  },
  {
    id: 'qry-103',
    query: 'Plan a California coast summer road trip starting from SF to San Diego with scenic stops',
    category: 'Travel',
    user: 'Sarah Chen',
    userEmail: 'sarah.chen@voyager.co',
    userAvatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=100&h=100&fit=crop&crop=face',
    model: 'Monogram-GPT',
    status: 'Success',
    responseTime: 4.2,
    timestamp: '12 mins ago',
    tokensPrompt: 92,
    tokensCompletion: 680,
    cost: 0.0078,
    fullPrompt: 'Plan a 7-day California Pacific Coast Highway road trip itinerary from San Francisco down to San Diego. Emphasize coastal views, Big Sur, and boutique hotels.',
    responseText: '### 7-Day Pacific Coast Highway (Highway 1) Itinerary\n- **Day 1:** San Francisco to Monterey & Carmel-by-the-Sea (17-Mile Drive)\n- **Day 2:** Big Sur cliffs, Bixby Bridge, McWay Falls to Cambria\n- **Day 3:** Santa Barbara & wine tasting in Santa Ynez Valley\n- **Day 4-5:** Malibu & Santa Monica coastal strolls\n- **Day 6-7:** Laguna Beach down to La Jolla & San Diego Balboa Park.',
    routingPath: 'SmartRouter > Monogram-GPT (us-west)',
    latencyBreakdown: { dnsMs: 22, ttftMs: 510, generationMs: 3668 },
    clientIp: '172.16.0.8',
    temperature: 0.7,
  },
  {
    id: 'qry-104',
    query: 'Which EV should I buy for a family of 4 with 300+ miles range and winter reliability?',
    category: 'General',
    user: 'Violet Norman',
    userEmail: 'violet.norman@example.com',
    userAvatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=100&h=100&fit=crop&crop=face',
    model: 'Monogram-GPT',
    status: 'Success',
    responseTime: 2.4,
    timestamp: '18 mins ago',
    tokensPrompt: 55,
    tokensCompletion: 380,
    cost: 0.0044,
    fullPrompt: 'Which EV should I buy for a family of 4 with 300+ miles range, spacious trunk, and strong cold-weather heat pump reliability under $55,000?',
    responseText: 'Top 3 EV Family contenders:\n1. **Hyundai Ioniq 5 AWD (Long Range)** - Superb 800V fast charging, roomy flat floor cabin, highly efficient heat pump.\n2. **Tesla Model Y Long Range** - 310-mile range, unmatched Supercharger network, great cold weather preconditioning.\n3. **Kia EV9** - If you need extra third-row flexibility.',
    routingPath: 'SmartRouter > Monogram-GPT (us-east)',
    latencyBreakdown: { dnsMs: 16, ttftMs: 410, generationMs: 1974 },
    clientIp: '192.168.1.42',
    temperature: 0.5,
  },
  {
    id: 'qry-105',
    query: 'Movies like Past Lives but lighter and romantic comedy style with bilingual themes',
    category: 'Movies',
    user: 'Amara Okafor',
    userEmail: 'amara.okafor@cinema.app',
    userAvatar: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=100&h=100&fit=crop&crop=face',
    model: 'Monogram-GPT',
    status: 'Success',
    responseTime: 2.1,
    timestamp: '25 mins ago',
    tokensPrompt: 42,
    tokensCompletion: 290,
    cost: 0.0033,
    fullPrompt: 'Give me movies with that wistful fate/destiny feeling of Past Lives, but lighter, humorous, with romantic comedy warmth and cultural duality.',
    responseText: 'Films with similar cross-cultural tenderness and romance:\n1. **Before Sunrise (1995)** - Serendipity, conversational chemistry, European setting.\n2. **Rye Lane (2023)** - Vibrant London art rom-com with unforgettable charm.\n3. **Always Be My Maybe (2019)** - Childhood sweethearts reunited in adulthood with hilarious banter.\n4. **Brooklyn (2015)** - Poignant warmth between two worlds.',
    routingPath: 'SmartRouter > Monogram-GPT (eu-central)',
    latencyBreakdown: { dnsMs: 20, ttftMs: 340, generationMs: 1740 },
    clientIp: '82.165.197.1',
    temperature: 0.8,
  },
  {
    id: 'qry-106',
    query: 'Plan a surprise birthday dinner schedule with 12 guests, catering timings and RSVP flow',
    category: 'Planning',
    user: 'Michael Reyes',
    userEmail: 'm.reyes@creativeagency.com',
    userAvatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=100&h=100&fit=crop&crop=face',
    model: 'Monogram-GPT',
    status: 'Failed',
    responseTime: 12.0,
    timestamp: '32 mins ago',
    tokensPrompt: 110,
    tokensCompletion: 12,
    cost: 0.0012,
    fullPrompt: 'Generate a detailed minute-by-minute coordinator schedule for a surprise party with 12 VIP guests, live jazz trio setup, and synchronized dinner courses.',
    responseText: '[Error: Gateway timeout after 12.0s while executing function call calendar_sync_v2]',
    routingPath: 'SmartRouter > Agent Tool Pipeline > Gateway Timeout',
    latencyBreakdown: { dnsMs: 25, ttftMs: 11975, generationMs: 0 },
    failureReason: 'External tool call calendar_sync_v2 timed out after 12000ms',
    clientIp: '64.233.160.1',
    temperature: 0.6,
  },
  {
    id: 'qry-107',
    query: 'Best late-night ramen open past 1 AM in Soho with vegetarian broth and craft sake',
    category: 'Restaurant',
    user: 'Guest 8842',
    userEmail: 'guest_8842@anon-session.net',
    userAvatar: undefined,
    model: 'Monogram-GPT',
    status: 'Success',
    responseTime: 1.8,
    timestamp: '40 mins ago',
    tokensPrompt: 38,
    tokensCompletion: 240,
    cost: 0.0028,
    fullPrompt: 'Best late-night ramen open past 1 AM in Soho with rich vegetarian mushroom or truffle broth.',
    responseText: '1. **Tonkotsu Soho (Dean St)** - Open till 2:00 AM on weekends; rich Shiitake & Kombu vegan ramen.\n2. **Bone Daddies Peter St** - Late service with signature spicy sesame tofu ramen.\n3. **Shoryu Soho** - Excellent plant-based White Natural broth with charred bamboo shoots.',
    routingPath: 'SmartRouter > Edge Cache Hit > Monogram-GPT (uk-south)',
    latencyBreakdown: { dnsMs: 12, ttftMs: 240, generationMs: 1548 },
    clientIp: '185.86.151.11',
    temperature: 0.6,
  },
  {
    id: 'qry-108',
    query: 'Write a toast that roasts my boss jokingly without crossing HR line at annual gala',
    category: 'Restaurant',
    user: 'Leo Bergström',
    userEmail: 'leo.b@nordicgroup.se',
    userAvatar: 'https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?w=100&h=100&fit=crop&crop=face',
    model: 'Monogram-GPT',
    status: 'Flagged',
    responseTime: 2.6,
    timestamp: '45 mins ago',
    tokensPrompt: 52,
    tokensCompletion: 280,
    cost: 0.0034,
    fullPrompt: 'Write a savage roast for my boss at the end-of-year dinner about his constant micromanaging and 6 AM calendar invites.',
    responseText: '"Ladies and gentlemen, let us raise our glasses to our fearless leader, David. A man who believes 6:00 AM isn\'t just a time on the clock—it\'s an invitation to sync. David, we love your dedication, your boundless energy, and especially the fact that you haven\'t scheduled a meeting for the next 20 minutes. Cheers!"',
    routingPath: 'SmartRouter > Moderation Guardrail > Monogram-GPT',
    latencyBreakdown: { dnsMs: 16, ttftMs: 440, generationMs: 2144 },
    flagReason: 'Moderation Guardrail: Potential workplace interpersonal sensitivity / mild roasting detected (Approved with caution).',
    clientIp: '194.71.107.15',
    temperature: 0.85,
  },
  {
    id: 'qry-109',
    query: 'Refactor this TypeScript React hook to eliminate memory leaks and unnecessary rerenders',
    category: 'Coding',
    user: 'Sarah Chen',
    userEmail: 'sarah.chen@voyager.co',
    userAvatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=100&h=100&fit=crop&crop=face',
    model: 'Claude 3.5',
    status: 'Success',
    responseTime: 1.9,
    timestamp: '1 hour ago',
    tokensPrompt: 145,
    tokensCompletion: 420,
    cost: 0.0057,
    fullPrompt: 'Optimize useWebSocketSubscription custom hook to properly clear intervals on unmount and use useRef for event listeners.',
    responseText: 'Here is the cleaned implementation using `useRef` to store the callback reference and a strict cleanup return in `useEffect`...',
    routingPath: 'SmartRouter > Claude 3.5 Sonnet (us-east)',
    latencyBreakdown: { dnsMs: 14, ttftMs: 310, generationMs: 1576 },
    clientIp: '172.16.0.8',
    temperature: 0.2,
  },
  {
    id: 'qry-110',
    query: 'Calculate quarterly burn rate and runway given $3.2M cash and $180k monthly spend',
    category: 'Finance',
    user: 'Marcus Vance',
    userEmail: 'mvance@apexholdings.vc',
    userAvatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=100&h=100&fit=crop&crop=face',
    model: 'GPT-5',
    status: 'Success',
    responseTime: 2.8,
    timestamp: '1 hour ago',
    tokensPrompt: 45,
    tokensCompletion: 290,
    cost: 0.0062,
    fullPrompt: 'Calculate quarterly burn rate and cash runway for $3,200,000 treasury with gross monthly burn $180,000 and 15% revenue growth.',
    responseText: '- **Quarterly Gross Burn:** $540,000 / quarter\n- **Effective Runway:** ~17.8 months (without revenue offset)\n- **Net Runway at 15% ARR ramp:** ~22.4 months before series B milestone.',
    routingPath: 'SmartRouter > High Precision > GPT-5',
    latencyBreakdown: { dnsMs: 18, ttftMs: 460, generationMs: 2322 },
    clientIp: '54.210.12.9',
    temperature: 0.1,
  },
  {
    id: 'qry-111',
    query: 'Differential diagnosis for pediatric low-grade fever with mild macular rash after amoxicillin',
    category: 'Healthcare',
    user: 'Dr. Elena Rostova',
    userEmail: 'e.rostova@healthsystem.org',
    userAvatar: 'https://images.unsplash.com/photo-1559839734-2b71ea197ec2?w=100&h=100&fit=crop&crop=face',
    model: 'Custom AI',
    status: 'Flagged',
    responseTime: 3.4,
    timestamp: '2 hours ago',
    tokensPrompt: 82,
    tokensCompletion: 380,
    cost: 0.0041,
    fullPrompt: 'Differential diagnosis: 4-year-old presenting with maculopapular rash on day 6 of amoxicillin therapy for otitis media. Afebrile currently.',
    responseText: 'Clinical differentials include:\n1. Non-allergic aminopenicillin rash (common in viral co-infections like EBV)\n2. Type IV delayed cutaneous drug reaction\n3. Roseola infantum late exanthem\n*Disclaimer: For physician reference only; clinical exam required.*',
    routingPath: 'SmartRouter > HIPAA Guarded > Custom Bio-LLM',
    latencyBreakdown: { dnsMs: 22, ttftMs: 510, generationMs: 2868 },
    flagReason: 'Clinical Safety: High-stakes medical advice safeguard activated. Disclaimer inserted.',
    clientIp: '131.215.1.20',
    temperature: 0.2,
  },
  {
    id: 'qry-112',
    query: 'Analyze sentiment and extract key entity mentions from this 500-page earnings transcript',
    category: 'Finance',
    user: 'Marcus Vance',
    userEmail: 'mvance@apexholdings.vc',
    userAvatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=100&h=100&fit=crop&crop=face',
    model: 'Gemini 1.5',
    status: 'Success',
    responseTime: 3.9,
    timestamp: '3 hours ago',
    tokensPrompt: 14200,
    tokensCompletion: 890,
    cost: 0.0185,
    fullPrompt: 'Process multi-part earnings transcript: extract CapEx guidance, cloud revenue acceleration, and competitor mentions.',
    responseText: 'Key highlights:\n- Cloud ARR surpassed $4.1B (+31% YoY)\n- AI infrastructure CapEx increased by $850M\n- Competitor mentions: AWS (4x), Azure (6x), Google Cloud (3x)',
    routingPath: 'SmartRouter > Long Context Route > Gemini 1.5 Pro',
    latencyBreakdown: { dnsMs: 24, ttftMs: 980, generationMs: 2896 },
    clientIp: '54.210.12.9',
    temperature: 0.3,
  },
];

export const MODEL_METRICS: ModelMetric[] = [
  {
    name: 'Monogram-GPT',
    queriesCount: 16420,
    avgLatency: 2.3,
    successRate: 98.4,
    costPer1k: 0.0015,
    color: '#8B5CF6',
  },
  {
    name: 'GPT-5',
    queriesCount: 4210,
    avgLatency: 2.7,
    successRate: 99.1,
    costPer1k: 0.0080,
    color: '#10B981',
  },
  {
    name: 'Claude 3.5',
    queriesCount: 2840,
    avgLatency: 1.9,
    successRate: 98.8,
    costPer1k: 0.0045,
    color: '#F59E0B',
  },
  {
    name: 'Gemini 1.5',
    queriesCount: 1080,
    avgLatency: 3.2,
    successRate: 97.6,
    costPer1k: 0.0025,
    color: '#3B82F6',
  },
  {
    name: 'Custom AI',
    queriesCount: 342,
    avgLatency: 1.6,
    successRate: 99.5,
    costPer1k: 0.0008,
    color: '#EC4899',
  },
];

export const CATEGORY_BREAKDOWN = [
  { name: 'Restaurant', count: 7420, percentage: 30, color: '#8B5CF6' },
  { name: 'Recipe', count: 4890, percentage: 20, color: '#EC4899' },
  { name: 'Travel', count: 3950, percentage: 16, color: '#F59E0B' },
  { name: 'Coding', count: 3120, percentage: 13, color: '#3B82F6' },
  { name: 'Finance', count: 2450, percentage: 10, color: '#10B981' },
  { name: 'General', count: 1820, percentage: 7, color: '#64748B' },
  { name: 'Movies', count: 1242, percentage: 4, color: '#6366F1' },
];

export const HOURLY_USAGE_TREND = [
  { time: '00:00', queries: 420, failed: 22, latency: 1.8 },
  { time: '04:00', queries: 280, failed: 12, latency: 1.6 },
  { time: '08:00', queries: 1420, failed: 45, latency: 2.1 },
  { time: '12:00', queries: 3840, failed: 110, latency: 2.5 },
  { time: '16:00', queries: 4620, failed: 135, latency: 2.6 },
  { time: '20:00', queries: 3120, failed: 85, latency: 2.2 },
  { time: '23:59', queries: 1890, failed: 40, latency: 1.9 },
];

export const SYSTEM_NOTIFICATIONS = [
  {
    id: 'notif-1',
    title: 'Model Routing Switched',
    message: 'Monogram-GPT fallback to Claude 3.5 was triggered for 42 coding queries.',
    time: '8m ago',
    type: 'info',
    unread: true,
  },
  {
    id: 'notif-2',
    title: 'Flagged Prompt Alert',
    message: 'User Leo Bergström triggered workplace humor policy check.',
    time: '45m ago',
    type: 'warning',
    unread: true,
  },
  {
    id: 'notif-3',
    title: 'Latency Spike Resolved',
    message: 'Calendar API integration timeout resolved on us-central cluster.',
    time: '2h ago',
    type: 'success',
    unread: false,
  },
];
